### PR TITLE
- Warn user if some card don't follow global regulatory domain

### PR DESCRIPTION
**Pull request by KeyofBlueS**

### CODE REVIEW

**Comment by Bogdan107** [comment]
Output now:
```
> 2                                                                                                                                                                                                                
Setting regulatory domain...                                                                                                                                                                                       
Current regulatory domain is:                                                                                                                                                                                      
WARNING one or more interfaces may not follow global regulatory domain                                                                                                                                             
global                                                                                                                                                                                                             
country BZ: DFS-JP                                                                                                                                                                                                 
--                                                                                                                                                                                                                 
phy#0                                                                                                                                                                                                              
country 00: DFS-UNSET
```

**Comment by KeyofBlueS** [comment]
Have You set the regulatory domain to "regulatory_domain=BR" in the "USER CONFIG SECTION" of the plugin?

**Comment by Bogdan107** [comment]
> Have You set the regulatory domain to "regulatory_domain=BR" in the "USER CONFIG SECTION" of the plugin?

Sorry...
I have BZ, but think that have BR...
Brazil - BR, not BZ.

**Comment by Bogdan107** [comment]
At now, after airgeddon exit, regulatory domain stay on that, which regdomain plugin set.
May you improve restoring regulatory domain at exit (posthook for exit_script_option function)?

**Comment by KeyofBlueS** [comment]
Yes I could, but let's open a separate issue for that

**Pull request merged**
